#!/bin/bash

set -e -o pipefail

# Build directories are now per-job so they'll never be reused and we should
# definitely clean them up.

# XXX: We can't do this here if configured with artifacts as this hook is
# called before the artifacts are uploaded. We'll do it in the post-artifact
# hook instead. But if there are no artifacts then this is the last hook.
if [[ -z "$BUILDKITE_ARTIFACT_PATHS" ]]; then
  rm -rf "$BUILDKITE_BUILD_CHECKOUT_PATH"
fi
