#!/bin/bash

set -e -o pipefail

# Remove both the worktree checkout and the corresponding directory from .git/worktrees in the shared git dir
git -C "$BUILDKITE_BUILD_CHECKOUT_PATH" worktree remove .
